Thought.create content: "I can picture in my mind a world without war, a world without hate. And I can picture us attacking that world, because they'd never expect it."
Thought.create content: "For mad scientists who keep brains in jars, here's a tip: why not add a slice of lemon to each jar, for freshness?"
Thought.create content: "Children need encouragement. If a kid gets an answer right, tell him it was a lucky guess. That way he develops a good, lucky feeling."
Thought.create content: "If a kid asks where rain comes from, I think a cute thing to tell him is \"God is crying.\" And if he asks why God is crying, another cute thing to tell him is 'Probably because of something you did.'"
Thought.create content: "If you're a cowboy and you're dragging a guy behind your horse, I bet it would really make you mad if you looked back and the guy was reading a magazine."
Thought.create content: "If you ever fall off the Sears Tower, just go real limp, because maybe you'll look like a dummy and people will try to catch you because, hey, free dummy."
Thought.create content: "It takes a big man to cry, but it takes a bigger man to laugh at that man."
Thought.create content: "If God dwells inside us, like some people say, I sure hope He like enchiladas, because that's what He's getting!"
Thought.create content: "One thing kids like is to be tricked. For instance, I was going to take my little nephew to Disneyland, but instead I drove him to an old burned-out warehouse. 'Oh, no,' I said, 'Disneyland burned down.' He cried and cried, but I think that deep down he thought it was a pretty good joke. I started to drive over to the real Disneyland, but it was getting pretty late."
Thought.create content: "Before you criticize someone, you should walk a mile in their shoes. That way, when you criticize them, you're a mile away and you have their shoes."
Thought.create content: "To me, clowns aren't funny. In fact, they're kind of scary. I've wondered where this started and I think it goes back to the time I went to the circus, and a clown killed my dad."
Thought.create content: "I hope if dogs ever take over the world, and they chose a king, they don't just go by size, because I bet there are some Chihuahuas with some good ideas."
Thought.create content: "If you're in a war, instead of throwing a hand grenade at the enemy, throw one of those small pumpkins. Maybe it'll make everyone think how stupid war is, and while they are thinking, you can throw a real grenade at them."
Thought.create content: "Dad always thought laughter was the best medicine, which I guess is why several of us died of tuberculosis."
Thought.create content: "When I was a kid my favorite relative was Uncle Caveman. After school we'd all go play in his cave, and every once in a while he would eat one of us. It wasn't until later that I found out that Uncle Caveman was a bear."
